apiVersion: 1

datasources:
  - name: InfluxDB-BESS
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: bess
      defaultBucket: telemetry
      tlsSkipVerify: false
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    editable: true
